version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - triple-mileage-app-1
      - triple-mileage-app-2
  triple-mileage-app-1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - env/app.env
    depends_on:
      - db-mysql
  triple-mileage-app-2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - env/app.env
    depends_on:
      - db-mysql
  db-mysql:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env