version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - triple-mileage-app-1
      - triple-mileage-app-2
  triple-mileage-app-1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - env/app.env
    depends_on:
      - db-mysql
      - kafka
  triple-mileage-app-2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - env/app.env
    depends_on:
      - db-mysql
      - kafka
  db-mysql:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  redis:
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - "6379:6379"